# Generated by Django 4.2.7 on 2023-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('Price', models.IntegerField(verbose_name=3500)),
            ],
        ),
    ]
